import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  ManyToOne,
  CreateDateColumn,
  UpdateDateColumn,
  DeleteDateColumn,
  OneToMany,
} from 'typeorm';
import { User } from '../../user/entities/user.entity';
import { Piece } from 'src/piece/entities/piece.entity';


@Entity()
export class Gabarit {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  name: string;

  @Column({nullable: true})
  description: String;

  // The original image uploaded by the user (immutable once created)
  @Column({ nullable: true })
  originalImage: string;

  // The latest processed image generated by the pipeline (can change over time)
  @Column({ nullable: true })
  processedImage: string; 

  @Column()
  iconPath: string;

  @ManyToOne(() => User, user => user.gabarits, { onDelete: 'CASCADE', nullable: false })
  user: User;

  @OneToMany(() => Piece, piece => piece.gabarit)
  pieces: Piece[];

  @CreateDateColumn()
  createdAt: Date;

  @Column({ type: 'float', nullable: false, comment: 'scale used for picture to real life resizeing : 1 pixel in the picture corresponds to X cm in real life', default: 1 })
  scale: number;
  @Column({ default: false })
  favorited: boolean;
  
  @UpdateDateColumn()
  updatedAt: Date;

  @DeleteDateColumn()
  deletedAt?: Date; 

}
